version: "3.5"

services:
  db:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - hotosm-poc-net

  api:
    build: ./api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - hotosm-poc-net

  web:
    build: ./ui
    depends_on:
      - api
    expose:
      - 3000
    ports:
      - 3000:3000

volumes:
  postgres_data:

networks:
  hotosm-poc-net:
