[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "bshankar", email = "ebhavanishankar@gmail.com"},
]
dependencies = [
    "fastapi[all]>=0.92.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}
